project_id = "edfloyhwqovslovzvkrm"

[functions.scan-business]
verify_jwt = false

[functions.test-google-api]
verify_jwt = false

[functions.search-business-details]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false