// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edfloyhwqovslovzvkrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkZmxveWh3cW92c2xvdnp2a3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjc3NTksImV4cCI6MjA2NjgwMzc1OX0.7ceXY-AFADk85vFTdXidkh2CW1Gq9XoDOJFJk9btfnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});